services:
  postgres:
    image: 'postgres:13.1-alpine'
    environment:
      - 'POSTGRES_DB=passenger-cloud'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '54322:5432'
