server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8061/eureka/
  instance:
    hostname: transport-service
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.rigoberto.transport

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres-transport:5432/transport-cloud
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        global_quote_identifiers: true
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0