server:
  port: 8060

spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transport-service
          uri: lb://transport-service
          predicates:
            - Path=/transport/**
          filters:
            - RewritePath=/transport/(?<path>.*), /$\{path}
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passenger/**
          filters:
            - RewritePath=/passenger/(?<path>.*), /$\{path}

eureka:
  client:
    enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  tracing:
    sampling:
      probability: 1.0